name: test

on:
  push:
  pull_request:
  schedule:
    - cron: "51 3 * * 6" # Runs at 03:51, only on Saturday
jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: ["ubuntu", "macos", "windows"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - name: Run tests without multithreading
        run: crystal spec
      - name: Run tests with env without multithreading
        run: crystal spec
        env:
          CRYSTAL_WORKERS: 3
      - name: Run tests with multithreading
        run: crystal spec -Dpreview_mt
      - name: Run tests with env with multithreading
        run: crystal spec -Dpreview_mt
        env:
          CRYSTAL_WORKERS: 3
